### ISSUE TITLE
插件入口

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#53] opened 2018-11-26 02:26 UTC
刚进去 就报错 bundling failed: TypeError: Cannot read property 'bindings' of null  这个啥意思啊  

import React from 'react';
    import {Package,Device,Service,Host} from 'miot';
    import {PackageEvent, DeviceEvent} from 'miot';
    import App from './Home.js';
    import {Entrance} from "../../miot-sdk";

    switch(Package.entrance){
        case Entrance.Main:
            Package.entry(App, _=>{
                //do something when the App is ready but not loaded
            })
            break;
        default:
            break;
    }

export default class App extends React.Component {
    render(){
        return <View>
            <Text>device model is : 23232</Text>
        </View>
    }
}
不知道什么鬼，我啥也没开始写

**Comment by kasparovfeng** [comment] 2018-11-26 02:29
<Text>device model is : 23232</Text>

**Comment by kasparovfeng** [comment] 2018-11-26 02:30
那个return 是对的，复制代码不知道咋没了text组建

**Comment by kasparovfeng** [comment] 2018-11-26 02:33
Loading dependency graph, done.
::ffff:10.8.20.234 - - [26/Nov/2018:02:32:30 +0000] "GET /projects/com.huami.watch3.ios/config.plist HTTP/1.1" 404 181 "-" "%E7%B1%B3%E5%AE%B6Beta/4.5.0.3 CFNetwork/902.2 Darwin/17.7.0"
error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/scope/index.js:867:13)
    at BlockScoping.updateScopeInfo (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/node_modules/@babel/traverse/lib/context.js:118:16)
 BUNDLE  [ios, dev] projects/com.huami.watch3.ios/index.ios.js ▓▓▓▓▓▓▓▓░░░░░░░░ 51.0% (10/14)::ffff:10.8.20.234 - - [26/Nov/2018:02:32:30 +0000] "GET /projects/com.huami.watch3.ios/index.ios.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "%E7%B1%B3%E5%AE%B6Beta/4.5.0.3 CFNetwork/902.2 Darwin/17.7.0"
 BUNDLE  [ios, dev] projects/com.huami.watch3.ios/index.ios.js ▓▓▓▓▓▓▓▓░░░░░░░░ 51.0% (10/14), failed.

**Comment by kasparovfeng** [comment] 2018-11-26 02:33
插件日志

**Comment by pencilCool** [comment] 2018-11-27 02:13
你好.
你说什么都没改。这样是不行的。请参考迁移手册
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E8%BF%81%E7%A7%BB%E6%89%8B%E5%86%8C.md

**Comment by kasparovfeng** [comment] 2018-11-27 02:44
麻烦看下我的问题啊，以前的业务还没集成哦，我刚创建了一个项目，入口就进不去啊 ，我就添加了一个入口，请正视我的问题，大哥哥

**Comment by laohuang88** [comment] 2018-11-27 06:37
你先创建一个空项目，除了配置外，什么都不做，看看运行起来有什么问题没有。

**Comment by kasparovfeng** [comment] 2018-11-27 06:54
你好，开发者，就是创建空的项目。然后在米家新版测试APP，上面调试入口添加了模块跟包名跟IP，然后点进去就报错了bindings 为null哦，什么都没干哦，Android我还没开始试，下午我试一下，我是IOS开发的

**Comment by LiuMengzhou** [comment] 2018-11-27 09:08
Duplicate of #57

**Closed** 2018-11-27 09:08 UTC
