### ISSUE TITLE
IOS蓝牙发现services个数比android少，chars字符串也不同于android，读取某个char值也错乱！

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#51] opened 2018-11-23 05:29 UTC
IOS蓝牙能连接发现服务和特征值了，但有几个小问题：

1， 在IOS上仅仅发现了3个service（fe95和自定义的有了），android是5个,；
      IOS上的services、chars和android上services、chars对应的字符串也不同，可能是跟IOS和android的系统处理有关系；

2，读取自定义的service中的几个chars的初始值，只有其中一个char有结果，但返回了其他的char值。

     同时，这几个chars值在bluetoothCharacteristicValueChanged的回调中，能一一对应，并且都正确 ！

**Comment by Banjiemin** [comment] 2018-11-23 05:30
// 5个services
const SERVICE_1800 = "00001800-0000-1000-8000-00805f9b34fb";
const SERVICE_1801 = "00001801-0000-1000-8000-00805f9b34fb";
const SERVICE_0203 = "00010203-0405-0607-0809-0a0b0c0d1912";
const SERVICE_FE95 = "0000fe95-0000-1000-8000-00805f9b34fb";
const SERVICE_FE01 = "0000fe01-0000-1000-8000-00805f9b34fb";

const SERVICE_0203_IOS = "00010203-0405-0607-0809-0A0B0C0D1912";
const SERVICE_FE95_IOS = "FE95";
const SERVICE_FE01_IOS = "FE01";

// 自定义的service(fe01)下的5个chars
const CHARS_0XFE01_0001_POWER = "00000001-0000-1000-8000-00805f9b34fb";
const CHARS_0XFE01_0002_LEFT = "00000002-0000-1000-8000-00805f9b34fb";
const CHARS_0XFE01_0003_TIMER_INDEX = "00000003-0000-1000-8000-00805f9b34fb";
const CHARS_0XFE01_0004_TIMER_CONTENT = "00000004-0000-1000-8000-00805f9b34fb";
const CHARS_0XFE01_0005_LINUX_STAMP = "00000005-0000-1000-8000-00805f9b34fb";

const CHARS_0XFE01_0001_POWER_IOS = "0001";
const CHARS_0XFE01_0002_LEFT_IOS = "0002";
const CHARS_0XFE01_0003_TIMER_INDEX_IOS = "0003";
const CHARS_0XFE01_0004_TIMER_CONTENT_IOS = "0004";
const CHARS_0XFE01_0005_LINUX_STAMP_IOS = "0005";

**Comment by edwardair** [comment] 2018-11-23 05:31
请问你们蓝牙连接成功了？能发下连接蓝牙的代码看看，我这边一直报错

**Comment by Banjiemin** [comment] 2018-11-23 05:32
还有一个小小的问题：

this._s6 = BluetoothEvent.bluetoothConnectionStatusChanged.addListener((mac, isConnect) => {
            this.log("bluetoothConnectionStatusChanged" + ",\n" + "mac = " + mac + ", bt.mac = " + device_bt.mac + ",\n" + "isConnected = " + isConnect);

            //if (device_bt.mac === mac && isConnect) {
            if (isConnect) {
                this.log("bluetooth connected");
            } else {
                //this.state.chars.clear();
                this.log("bluetooth not connect");
            }
        })


android上mac就是一个字符串，但IOS上是一个object ！

**Comment by Banjiemin** [comment] 2018-11-23 05:41
> 请问你们蓝牙连接成功了？能发下连接蓝牙的代码看看，我这边一直报错


我就简单的copy点代码给你看看了啊：

const device_bt = Device.bluetooth;

connect() {
        this.log("start connect(): bt.isConnected = " + device_bt.isConnected)
        if (device_bt.isConnected) {
            this.log("connected1111");
            device_bt.startDiscoverServices(SERVICE_1,
                SERVICE_2,
                SERVICE_3,
                SERVICE_4,
                SERVICE_5);

        } else {
            this.log("connected2222:");
            device_bt.connect(0).then((data) => {
                this.log("connected3333: bt.isConnected = " + device_bt.isConnected);
                device_bt.startDiscoverServices(SERVICE_1,
                    SERVICE_2,
                    SERVICE_3,
                    SERVICE_4,
                    SERVICE_5);
            }).catch((data) => {
                this.log("connect error:" + data);//链接失败的页面
                if (data.code === -7) {
                    this.log("buttonText: timeout retrying")
                    this.connect();
                } else {
                    this.log("buttonText: click retry\n" + JSON.stringify(data))
                }
            });
        }
    }



componentDidMount() {
        
        // 连接
        this.connect();

        // 定义Event，发现service和characters
        this._s1 = BluetoothEvent.bluetoothSeviceDiscovered.addListener((blut, services) => {
            this.log("bluetoothSeviceDiscovered: " + "\nMac = " + blut.mac + "\n Services = " +
                services.map(s => s.UUID) + "\n" + "bt.isConnected = " + device_bt.isConnected)

            if (device_bt.isConnected) {
                services.forEach(s => {
                    if (s.UUID === SERVICE_1) {
                    } else if (s.UUID === SERVICE_2) {
                    } else if (s.UUID === SERVICE_3 || s.UUID === SERVICE_3_IOS) {
                    } else if (s.UUID === SERVICE_4 || s.UUID === SERVICE_4_IOS) {
                    } else if (s.UUID === SERVICE_5 || s.UUID === SERVICE_5_IOS) {
                        this.log("5: my service")
                        s.startDiscoverCharacteristics(CHARS_0XFE01_0001_POWER,
                            CHARS_0XFE01_0002_LEFT,
                            CHARS_0XFE01_0003_TIMER_INDEX,
                            CHARS_0XFE01_0004_TIMER_CONTENT,
                            CHARS_0XFE01_0005_LINUX_STAMP);
                    }
                })
            } else {
                this.connect();
            }
        })
        this._s2 = BluetoothEvent.bluetoothCharacteristicDiscovered.addListener((bluetooth, service, characters) => {
            this.log("bluetoothCharacteristicDiscovered:" + ",\n" + "ServiceName:" + service.UUID
                + ",\n" + "chars:" + characters.map(s => s.UUID) + "\n" + "bt.isConnected = " + device_bt.isConnected);

            if (device_bt.isConnected) {

                // 暂时先处理FE01下的chars
                if (service.UUID == SERVICE_5 || service.UUID == SERVICE_5_IOS) {
                    this.log("!!! this my service !!!")
                    this.bt.service.myservice = device_bt.getService(service.UUID);
                    characters.forEach(c => {
                        if (c.UUID == CHARS_0XFE01_0001_POWER || c.UUID == CHARS_0XFE01_0001_POWER_IOS) {
                            this.log("1: 0001 - power");
                            this.bt.chars._power = this.bt.service.myservice.getCharacteristic(c.UUID);
                        } else if (c.UUID == CHARS_0XFE01_0002_LEFT || c.UUID == CHARS_0XFE01_0002_LEFT_IOS) {
                            this.log("2: 0002 - left");
                            this.bt.chars._left = this.bt.service.myservice.getCharacteristic(c.UUID);
                        } else if (c.UUID == CHARS_0XFE01_0003_TIMER_INDEX || c.UUID == CHARS_0XFE01_0003_TIMER_INDEX_IOS) {
                            this.log("3: 0003 - index");
                            this.bt.chars._timer_index = this.bt.service.myservice.getCharacteristic(c.UUID);
                        } else if (c.UUID == CHARS_0XFE01_0004_TIMER_CONTENT || c.UUID == CHARS_0XFE01_0004_TIMER_CONTENT_IOS) {
                            this.log("4: 0004 - content");
                            this.bt.chars._timer_content = this.bt.service.myservice.getCharacteristic(c.UUID);
                        } else if (c.UUID == CHARS_0XFE01_0005_LINUX_STAMP || c.UUID == CHARS_0XFE01_0005_LINUX_STAMP_IOS) {
                            this.log("5: 0005 - linux");
                            this.bt.chars._linux_stamp = this.bt.service.myservice.getCharacteristic(c.UUID);
                        }
                    });

                    // 获取初始化的开关值 ！
                    this.initValuesbyChars();
                }
            } else {
                this.connect();
            }
        })
        this._s3 = BluetoothEvent.bluetoothCharacteristicValueChanged.addListener((bluetooth, service, character, value) => {
            this.log("bluetoothCharacteristicValueChanged: serviceID = " + service.UUID + ", charID = " + character.UUID + ", value = " + value);//刷新界面
            if (service.UUID == SERVICE_FE01 || service.UUID == SERVICE_FE01_IOS) {
                if (character.UUID == CHARS_0XFE01_0001_POWER || character.UUID == CHARS_0XFE01_0001_POWER_IOS) {
                } else if (character.UUID == CHARS_0XFE01_0002_LEFT || character.UUID == CHARS_0XFE01_0002_LEFT_IOS) {
                } else if (character.UUID == CHARS_0XFE01_0004_TIMER_CONTENT || character.UUID == CHARS_0XFE01_0004_TIMER_CONTENT_IOS) {
                }
            }

        })
        this._s4 = BluetoothEvent.bluetoothSeviceDiscoverFailed.addListener((blut, data) => {
            this.log("bluetoothSeviceDiscoverFailed: " + data);
        })
        this._s5 = BluetoothEvent.bluetoothCharacteristicDiscoverFailed.addListener((blut, data) => {
            this.log("bluetoothCharacteristicDiscoverFailed: " + data);
        })
        this._s6 = BluetoothEvent.bluetoothConnectionStatusChanged.addListener((mac, isConnect) => {
            this.log("bluetoothConnectionStatusChanged" + ",\n" + "mac = " + mac + ", bt.mac = " + device_bt.mac + ",\n" + "isConnected = " + isConnect);

            //if (device_bt.mac === mac && isConnect) {
            if (isConnect) {
                this.log("bluetooth connected");
            } else {
                //this.state.chars.clear();
                this.log("bluetooth not connect");
            }
        })
    }

**Comment by edwardair** [comment] 2018-11-23 05:43
你们的是 connect(0)，小米蓝牙，我们的协议不一样，一直返回连接错误

**Comment by Banjiemin** [comment] 2018-11-23 05:45
> 你们的是 connect(0)，小米蓝牙，我们的协议不一样，一直返回连接错误

那就不了解啦，最后直接联系miot的工程师吧。

我也是参照他们给的demo呢 ！

**Comment by dingshaoran** [comment] 2018-11-26 03:58
不用管service个数一样不一样，按照 demo 上的发现服务逻辑使用你们的 service FE01 。
value 读取的值是 android、ios 哪个有问题请具体说一下

**Comment by dingshaoran** [comment] 2018-11-26 04:00
不需要区分 android 和 ios ，startDiscoverServices，bluetoothSeviceDiscovered，bluetoothCharacteristicDiscovered

**Comment by Banjiemin** [comment] 2018-11-26 04:09
services个数问题、字符问题可以不用管，我反正能找到自定义的FE01，

其中自定义的service下有chars： 0001、0002、0003、0004、0005， （其中0003和0005是write）

IOS上 读取0001、0002、0004的值，只返回了0004的，并且读的值是错乱到了0001的 ！
android上正常 ！

**Comment by LiuMengzhou** [comment] 2018-12-17 09:30
Duplicate of #134

**Closed by LiuMengzhou** 2018-12-17 09:30 UTC
Labels: 平台-iOS
