### ISSUE TITLE
提示Did you run react-native link?

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#24] opened 2018-11-12 10:44 UTC
安卓跑官方Demo，结果爆红提示:Something went wrong initializing the native ReactLocalization module.
Please check your configuration.
Did you run 'react-native link'?该打印位于LocalizeStrings.js文件中

**Comment by jimu380261652** [comment] 2018-11-13 01:27
报错截图

**Comment by jimu380261652** [comment] 2018-11-13 01:30
![_20181113092626](https://user-images.githubusercontent.com/11864517/48384746-ab173b00-e726-11e8-8260-17f547ad9f31.jpg)

**Comment by dingshaoran** [comment] 2018-11-13 06:52
请在 mac 或者 lunix 上使用此框架，暂时 window 的兼容性不好

**Comment by LiuMengzhou** [comment] 2018-11-13 14:15
Duplicate of #19

**Closed** 2018-11-13 14:15 UTC
