### ISSUE TITLE
快捷卡片设置问题

### ISSUE THREAD

**Issue by wyc123456** [MiEcosystem/miot-plugin-sdk#1167] opened 2019-07-09 09:05 UTC
**是否为新品（必填）**
在售

**关联的产品model**
xjx.toilet.pro
**项目ID（必填）**
无项目ID

**企业名称（必填）**
 厦门芯联科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
 iOS10.2
- SDK分支: [eg.master/10000/...]
 master
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
点击按钮，图片永远为normal状态的图片，文字为operation数组第二个对象的文字，点击按钮，显示都不会改变

**期望（必填）**
单次点击为开启功能(图片为normal，下面的文字为operation数组第一个对象的文字)
双次点击为关闭相应功能（图片为selected，下面的文字为operation数组第二个对象的文字）

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

卡片配置如下：
{
    "models":["xjx.toilet.pro"],
    "props":[
      {
        "prop_key": "prop.water_pos_t",
        "prop_extra": [
             {"param_range": {
              "min":1,
              "max":5
             },
             "desc": {
                "en": "Open",
                "zh_CN": "启动",
                "zh_TW": "啟動",
                "zh_HK": "啟動"
              }
            },
            {"param_range": {
              "min":6,
              "max":7
             },
             "desc": {
                "en": "Close",
                "zh_CN": "关闭",
                "zh_TW": "",
                "zh_HK": ""
              }
            }
        ]
      },
      {
        "prop_key": "prop.water_pos_w",
        "prop_extra": [
             {"param_range": {
              "min":1,
              "max":5
             },
             "desc": {
                "en": "Open",
                "zh_CN": "启动",
                "zh_TW": "啟動",
                "zh_HK": "啟動"
              }
            },
            {"param_range": {
              "min":6,
              "max":7
             },
             "desc": {
                "en": "Close",
                "zh_CN": "关闭",
                "zh_TW": "",
                "zh_HK": ""
              }
            }
          ]
    },
    {
      "prop_key": "prop.fan_temp",
      "prop_extra": [
           {"param_range": {
            "min":1,
            "max":5
           },
           "desc": {
              "en": "Open",
              "zh_CN": "启动",
              "zh_TW": "啟動",
              "zh_HK": "啟動"
            }
          },
          {"param_range": {
            "min":6,
            "max":7
           },
           "desc": {
              "en": "Close",
              "zh_CN": "关闭",
              "zh_TW": "",
              "zh_HK": ""
            }
          }
        ]
    }
  ],
    "cards":{ 
        "layout_type":4, 
        "card_items":[
            {
                "cardType": 1, 
                "prop_key": "prop.water_pos_t", 
                "operation": [                                
                    {
                      "button_image": {
                        "normal": "popup_icon_wind_hig",
                        "selected": "popup_icon_wind_nor",
                        "unable": "popup_icon_wind_disable"
                      },
                      "button_name": {                          
                        "zh_CN": "臀洗开启",
                        "en": "HipWash",
                        "zh_TW": "臀洗",
                        "zh_HK": "臀洗"
                      },
                      "prop_value": 2,
                      "method": "tun_wash_on",
                      "param": [
                        2,
                        2,
                        2,
                        1,
                        0
                      ]
                    },
                    {
                        "button_image": {
                          "normal": "",
                          "selected": "",
                          "unable": ""
                        },
                        "button_name": {                          
                          "zh_CN": "臀洗关闭",
                          "en": "HipWash",
                          "zh_TW": "臀洗",
                          "zh_HK": "臀洗"
                        },
                        "prop_value": 1,
                        "method": "func_off",
                        "param": [
                            "tun_wash"
                        ]
                      }
                ]
            },
            {
              "cardType": 1, 
              "prop_key": "prop.water_pos_w", 
              "operation": [                                
                  {
                    "button_image": {
                      "normal": "popup_icon_finecook_hig",
                      "selected": "popup_icon_finecook_nor"
                    },
                    "button_name": {                          
                      "zh_CN": "妇洗开启",
                      "en": "WomanWash",
                      "zh_TW": "婦洗",
                      "zh_HK": "婦洗"
                    },
                    "prop_value": 2,
                    "method": "women_wash_on",
                    "param": [
                      2,
                      2,
                      2,
                      1,
                      0
                    ]
                  },
                  {
                      "button_image": {
                        "normal": "",
                        "selected": ""
                      },
                      "button_name": {                          
                        "zh_CN": "妇洗关闭",
                        "en": "WomanWash",
                        "zh_TW": "婦洗",
                        "zh_HK": "婦洗"
                      },
                      "prop_value": 2,
                      "method": "func_off",
                      "param": [
                          "women_wash"
                      ]
                    }
              ]
          },
          {
            "cardType": 1, 
            "prop_key": "prop.fan_temp", 
            "operation": [                                
                {
                  "button_image": {
                    "normal": "popup_icon_sun_hig",
                    "selected": "popup_icon_sun_nor",
                    "unable": "popup_icon_sun_unable"
                  },
                  "button_name": {                          
                    "zh_CN": "烘干开启",
                    "en": "WarnDry",
                    "zh_TW": "烘乾",
                    "zh_HK": "烘乾"
                  },
                  "prop_value": 2,
                  "method": "warm_dry_on",
                  "param": [
                    2
                  ]
                },
                {
                    "button_image": {
                      "normal": "",
                      "selected": ""
                    },
                    "button_name": {                          
                      "zh_CN": "烘干关闭",
                      "en": "WarnDry",
                      "zh_TW": "烘乾",
                      "zh_HK": "烘乾"
                    },
                    "prop_value": 1,
                    "method": "func_off",
                    "param": [
                        "warm_dry"
                    ]
                  }
            ]
        }
        ]
    }
}
**不要贴大段代码❗️**

**Comment by zanetti4** [comment] 2019-07-09 10:30
Duplicate of #1095 
@hyunhui2006 这个和1095是一个问题，请查看

**Comment by santcool** [comment] 2019-07-24 03:58
请问这个能提供个测试账号吗？望尽快回复

**Closed** 2019-07-24 08:33 UTC
Labels: Native-iOS

**Comment by santcool** [comment] 2019-07-24 08:35
无人回复，暂且关闭，若有问题，请重开issue
